### ISSUE TITLE
Investigate making numeric_cast use BOOST_CONSTEXPR.

### ISSUE THREAD

**Issue by brandon-kohn** [boostorg/numeric_conversion#13]
TODO: I can't think of any reasons off the top of my head why this wouldn't work. I use numeric_cast to perform scaling conversions for a fixed_point type. This is required for the constructor of the fixed_point to be constexpr.

**Comment by tobiasleibner** [comment]
This has been closed as completed but there is no `constexpr` version of `numeric_cast`, is there? Do you remember what the outcome of this investigation was?
