### ISSUE TITLE
enums used with boost::mpl::integral_c may need to be extended.

### ISSUE THREAD

**Issue by dabrahams** [boostorg/numeric_conversion#24]
[This issue](https://github.com/boostorg/mpl/issues/69#issuecomment-1208905334) suggests that the enums being used with mpl::integral_c need two additional cases.  The problem was detected by the newest Clang in trunk.

**Comment by dabrahams** [comment]
This is wrong; MPL [can be fixed](https://godbolt.org/z/WY7e6o1WW)

**Comment by dabrahams** [comment]
Actually the easiest workaround is to add an underlying type (e.g. `int`) for each of these enums.

```cpp
enum example : int { zero };
constexpr example x{static_cast<example>(-1)};
```

**Comment by pdimov** [comment]
Can't add `: int` in C++03 libraries though.

**Comment by pdimov** [comment]
Something like this
```
enum int_float_mixture_enum
{
    // for mpl::integral_c<int_float_mixture_enum, integral_to_integral>
    int_float_mixture_enum_unused_first = -1,

    integral_to_integral,
    integral_to_float,
    float_to_integral,
    float_to_float,

    // for mpl::integral_c<int_float_mixture_enum, float_to_float>
    int_float_mixture_enum_unused_last
};
```
works, but then `switch` statements start generating "not all enumeration values handled in a switch" warnings. :-/

**Comment by pdimov** [comment]
[Switching to boost::integral_constant](https://github.com/boostorg/numeric_conversion/commit/50a1eae942effb0a9b90724323ef8f2a67e7984a) seems to work and is the least intrusive fix.

**Comment by pdimov** [comment]
Applied https://github.com/boostorg/numeric_conversion/commit/50a1eae942effb0a9b90724323ef8f2a67e7984a to develop.
